server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sigr_db
    username: sigr_user
    password: sigr_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
